"""x

Revision ID: 6e5f40388c07
Revises: 0be2ccc0f842
Create Date: 2018-07-31 11:56:54.289278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5f40388c07'
down_revision = '0be2ccc0f842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('resume_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'resume_url')
    # ### end Alembic commands ###
